# coding: utf-8

"""
    Aspose.Diagram Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

#from asposediagramcloud.apis.diagram_api import DiagramApi
#from asposediagramcloud.rest import ApiException
#import asposediagramcloud
import os
import sys
import unittest
import test_base

from asposediagramcloud.models import *

ABSPATH = os.path.abspath(os.path.realpath(os.path.dirname(__file__)) + "/..")
sys.path.append(ABSPATH)

localtestFile = "testData/FileUpload.vdx"
storageTestFOLDER = "SDKTests\\Python"
fileName="pageTest.vsdx"


class TestPage(unittest.TestCase):
    """ DiagramApi unit test stubs """

    def setUp(self):
        self.api = test_base.GetDiagramApi()
        self.storageApi = test_base.GetStorageApi()

    def tearDown(self):
        pass

    def test_create_new(self):
        """
        Test case for create_new

        Create Empty file into the specified format.
        """
        folder = storageTestFOLDER
        is_overwrite = "true"
        result = self.api.create_new(fileName, folder=folder, is_overwrite=is_overwrite)
        self.assertIsNotNone(result.created, 'Error has occurred while create file')
        pass

    def test_put_new(self):
        result=self.api.put_new_page(fileName, "newPage", folder = storageTestFOLDER)
        self.assertTrue(result.is_success)
        pass

    def test_post_page_setup(self):
        setting=PageSetting()
        setting.page_width=2
        setting.page_height=2
        result=self.api.post_page_setup(fileName, "Page-0", setting,folder = storageTestFOLDER)
        self.assertTrue(result.is_success)
        pass

    def test_get_pages(self):
        result=self.api.get_pages(fileName, folder = storageTestFOLDER)
        self.assertTrue(len(result.model)>0)
        pass

  

if __name__ == '__main__':
    unittest.main()
