# coding: utf-8

"""
    Aspose.Diagram Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import sys
from setuptools import setup, find_packages

NAME = "asposediagramcloud"
VERSION = "19.10"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil", "asposestoragecloud"]

setup(
    name=NAME,
    version=VERSION,
    description="Aspose.Diagram.Cloud for Python",
    author="asposecloud",
    author_email="aspose.cloud@aspose.com",
    url="https://github.com/aspose-diagram-cloud/aspose-diagram-cloud-python",
    keywords=["aspose", "diagram", "cloud"],
    install_requires=REQUIRES,
    packages=['asposediagramcloud', 'asposediagramcloud.apis', 'asposediagramcloud.models'],
    include_package_data=True,
    long_description="Aspose.Diagram Cloud SDK for Python allows you to use Aspose.Diagram APIs in your Python applications",
    classifiers=[
        'Programming Language :: Python :: 2.7',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
)
