# coding: utf-8

"""
    Aspose.Diagram Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re
from . import SaveOptionsModel

class DiagramSaveOptions(SaveOptionsModel):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'auto_fit_page_to_drawing_content': 'bool'
    }

    attribute_map = {
        'auto_fit_page_to_drawing_content': 'AutoFitPageToDrawingContent'
    }
    
    @staticmethod
    def get_swagger_types():
        return dict(DiagramSaveOptions.swagger_types, **SaveOptionsModel.get_swagger_types())
    
    @staticmethod
    def get_attribute_map():
        return dict(DiagramSaveOptions.attribute_map, **SaveOptionsModel.get_attribute_map())
    
    def get_from_container(self, attr):
        if attr in self.container:
            return self.container[attr]
        return None

    def __init__(self, auto_fit_page_to_drawing_content=None, **kw):
        super(DiagramSaveOptions, self).__init__(**kw)
		    
        """
        DiagramSaveOptions - a model defined in Swagger
        """

        self.container['auto_fit_page_to_drawing_content'] = None

        if auto_fit_page_to_drawing_content is not None:
          self.auto_fit_page_to_drawing_content = auto_fit_page_to_drawing_content

    @property
    def auto_fit_page_to_drawing_content(self):
        """
        Gets the auto_fit_page_to_drawing_content of this DiagramSaveOptions.

        :return: The auto_fit_page_to_drawing_content of this DiagramSaveOptions.
        :rtype: bool
        """
        return self.container['auto_fit_page_to_drawing_content']

    @auto_fit_page_to_drawing_content.setter
    def auto_fit_page_to_drawing_content(self, auto_fit_page_to_drawing_content):
        """
        Sets the auto_fit_page_to_drawing_content of this DiagramSaveOptions.

        :param auto_fit_page_to_drawing_content: The auto_fit_page_to_drawing_content of this DiagramSaveOptions.
        :type: bool
        """

        self.container['auto_fit_page_to_drawing_content'] = auto_fit_page_to_drawing_content

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.get_swagger_types()):
            value = self.get_from_container(attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, DiagramSaveOptions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
