# coding: utf-8

"""
    Aspose.Diagram Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re
from . import SaaSposeResponse

class ModifyResponse(SaaSposeResponse):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_success': 'bool',
        'message': 'str'
    }

    attribute_map = {
        'is_success': 'IsSuccess',
        'message': 'Message'
    }
    
    @staticmethod
    def get_swagger_types():
        return dict(ModifyResponse.swagger_types, **SaaSposeResponse.get_swagger_types())
    
    @staticmethod
    def get_attribute_map():
        return dict(ModifyResponse.attribute_map, **SaaSposeResponse.get_attribute_map())
    
    def get_from_container(self, attr):
        if attr in self.container:
            return self.container[attr]
        return None

    def __init__(self, is_success=None, message=None, **kw):
        super(ModifyResponse, self).__init__(**kw)
		    
        """
        ModifyResponse - a model defined in Swagger
        """

        self.container['is_success'] = None
        self.container['message'] = None

        self.is_success = is_success
        if message is not None:
          self.message = message

    @property
    def is_success(self):
        """
        Gets the is_success of this ModifyResponse.

        :return: The is_success of this ModifyResponse.
        :rtype: bool
        """
        return self.container['is_success']

    @is_success.setter
    def is_success(self, is_success):
        """
        Sets the is_success of this ModifyResponse.

        :param is_success: The is_success of this ModifyResponse.
        :type: bool
        """
        """
        if is_success is None:
            raise ValueError("Invalid value for `is_success`, must not be `None`")
        """

        self.container['is_success'] = is_success

    @property
    def message(self):
        """
        Gets the message of this ModifyResponse.

        :return: The message of this ModifyResponse.
        :rtype: str
        """
        return self.container['message']

    @message.setter
    def message(self, message):
        """
        Sets the message of this ModifyResponse.

        :param message: The message of this ModifyResponse.
        :type: str
        """

        self.container['message'] = message

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.get_swagger_types()):
            value = self.get_from_container(attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ModifyResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
