# coding: utf-8

"""
    Web API Swagger specification

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PageModel(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'page_name': 'str',
        'sharps': 'list[SharpModel]'
    }

    attribute_map = {
        'page_name': 'PageName',
        'sharps': 'Sharps'
    }
    
    @staticmethod
    def get_swagger_types():
        return PageModel.swagger_types
    
    @staticmethod
    def get_attribute_map():
        return PageModel.attribute_map
    
    def get_from_container(self, attr):
        if attr in self.container:
            return self.container[attr]
        return None

    def __init__(self, page_name=None, sharps=None, **kw):
        """
        Associative dict for storing property values
        """
        self.container = {}
		    
        """
        PageModel - a model defined in Swagger
        """

        self.container['page_name'] = None
        self.container['sharps'] = None

        if page_name is not None:
          self.page_name = page_name
        if sharps is not None:
          self.sharps = sharps

    @property
    def page_name(self):
        """
        Gets the page_name of this PageModel.

        :return: The page_name of this PageModel.
        :rtype: str
        """
        return self.container['page_name']

    @page_name.setter
    def page_name(self, page_name):
        """
        Sets the page_name of this PageModel.

        :param page_name: The page_name of this PageModel.
        :type: str
        """

        self.container['page_name'] = page_name

    @property
    def sharps(self):
        """
        Gets the sharps of this PageModel.

        :return: The sharps of this PageModel.
        :rtype: list[SharpModel]
        """
        return self.container['sharps']

    @sharps.setter
    def sharps(self, sharps):
        """
        Sets the sharps of this PageModel.

        :param sharps: The sharps of this PageModel.
        :type: list[SharpModel]
        """

        self.container['sharps'] = sharps

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.get_swagger_types()):
            value = self.get_from_container(attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PageModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
