# coding: utf-8

"""
    Aspose.Diagram Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PageSetting(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'name_u': 'str',
        'page_width': 'float',
        'page_height': 'float'
    }

    attribute_map = {
        'name': 'Name',
        'name_u': 'NameU',
        'page_width': 'PageWidth',
        'page_height': 'PageHeight'
    }
    
    @staticmethod
    def get_swagger_types():
        return PageSetting.swagger_types
    
    @staticmethod
    def get_attribute_map():
        return PageSetting.attribute_map
    
    def get_from_container(self, attr):
        if attr in self.container:
            return self.container[attr]
        return None

    def __init__(self, name=None, name_u=None, page_width=None, page_height=None, **kw):
        """
        Associative dict for storing property values
        """
        self.container = {}
		    
        """
        PageSetting - a model defined in Swagger
        """

        self.container['name'] = None
        self.container['name_u'] = None
        self.container['page_width'] = None
        self.container['page_height'] = None

        if name is not None:
          self.name = name
        if name_u is not None:
          self.name_u = name_u
        if page_width is not None:
          self.page_width = page_width
        if page_height is not None:
          self.page_height = page_height

    @property
    def name(self):
        """
        Gets the name of this PageSetting.
        Page Name

        :return: The name of this PageSetting.
        :rtype: str
        """
        return self.container['name']

    @name.setter
    def name(self, name):
        """
        Sets the name of this PageSetting.
        Page Name

        :param name: The name of this PageSetting.
        :type: str
        """

        self.container['name'] = name

    @property
    def name_u(self):
        """
        Gets the name_u of this PageSetting.
        Page Name

        :return: The name_u of this PageSetting.
        :rtype: str
        """
        return self.container['name_u']

    @name_u.setter
    def name_u(self, name_u):
        """
        Sets the name_u of this PageSetting.
        Page Name

        :param name_u: The name_u of this PageSetting.
        :type: str
        """

        self.container['name_u'] = name_u

    @property
    def page_width(self):
        """
        Gets the page_width of this PageSetting.
        Page Width

        :return: The page_width of this PageSetting.
        :rtype: float
        """
        return self.container['page_width']

    @page_width.setter
    def page_width(self, page_width):
        """
        Sets the page_width of this PageSetting.
        Page Width

        :param page_width: The page_width of this PageSetting.
        :type: float
        """

        self.container['page_width'] = page_width

    @property
    def page_height(self):
        """
        Gets the page_height of this PageSetting.
        Page Height

        :return: The page_height of this PageSetting.
        :rtype: float
        """
        return self.container['page_height']

    @page_height.setter
    def page_height(self, page_height):
        """
        Sets the page_height of this PageSetting.
        Page Height

        :param page_height: The page_height of this PageSetting.
        :type: float
        """

        self.container['page_height'] = page_height

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.get_swagger_types()):
            value = self.get_from_container(attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PageSetting):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
