# coding: utf-8

"""
    Aspose.Diagram Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re
from . import SaaSposeResponse

class SaveAsResponse(SaaSposeResponse):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'source_file': 'str',
        'saved_file': 'str',
        'additionals': 'list[str]'
    }

    attribute_map = {
        'source_file': 'SourceFile',
        'saved_file': 'SavedFile',
        'additionals': 'Additionals'
    }
    
    @staticmethod
    def get_swagger_types():
        return dict(SaveAsResponse.swagger_types, **SaaSposeResponse.get_swagger_types())
    
    @staticmethod
    def get_attribute_map():
        return dict(SaveAsResponse.attribute_map, **SaaSposeResponse.get_attribute_map())
    
    def get_from_container(self, attr):
        if attr in self.container:
            return self.container[attr]
        return None

    def __init__(self, source_file=None, saved_file=None, additionals=None, **kw):
        super(SaveAsResponse, self).__init__(**kw)
		    
        """
        SaveAsResponse - a model defined in Swagger
        """

        self.container['source_file'] = None
        self.container['saved_file'] = None
        self.container['additionals'] = None

        if source_file is not None:
          self.source_file = source_file
        if saved_file is not None:
          self.saved_file = saved_file
        if additionals is not None:
          self.additionals = additionals

    @property
    def source_file(self):
        """
        Gets the source_file of this SaveAsResponse.

        :return: The source_file of this SaveAsResponse.
        :rtype: str
        """
        return self.container['source_file']

    @source_file.setter
    def source_file(self, source_file):
        """
        Sets the source_file of this SaveAsResponse.

        :param source_file: The source_file of this SaveAsResponse.
        :type: str
        """

        self.container['source_file'] = source_file

    @property
    def saved_file(self):
        """
        Gets the saved_file of this SaveAsResponse.

        :return: The saved_file of this SaveAsResponse.
        :rtype: str
        """
        return self.container['saved_file']

    @saved_file.setter
    def saved_file(self, saved_file):
        """
        Sets the saved_file of this SaveAsResponse.

        :param saved_file: The saved_file of this SaveAsResponse.
        :type: str
        """

        self.container['saved_file'] = saved_file

    @property
    def additionals(self):
        """
        Gets the additionals of this SaveAsResponse.

        :return: The additionals of this SaveAsResponse.
        :rtype: list[str]
        """
        return self.container['additionals']

    @additionals.setter
    def additionals(self, additionals):
        """
        Sets the additionals of this SaveAsResponse.

        :param additionals: The additionals of this SaveAsResponse.
        :type: list[str]
        """

        self.container['additionals'] = additionals

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.get_swagger_types()):
            value = self.get_from_container(attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, SaveAsResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
