# coding: utf-8

"""
    Aspose.Diagram Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ShapeStyleData(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'back_ground_color': 'str'
    }

    attribute_map = {
        'back_ground_color': 'BackGroundColor'
    }
    
    @staticmethod
    def get_swagger_types():
        return ShapeStyleData.swagger_types
    
    @staticmethod
    def get_attribute_map():
        return ShapeStyleData.attribute_map
    
    def get_from_container(self, attr):
        if attr in self.container:
            return self.container[attr]
        return None

    def __init__(self, back_ground_color=None, **kw):
        """
        Associative dict for storing property values
        """
        self.container = {}
		    
        """
        ShapeStyleData - a model defined in Swagger
        """

        self.container['back_ground_color'] = None

        if back_ground_color is not None:
          self.back_ground_color = back_ground_color

    @property
    def back_ground_color(self):
        """
        Gets the back_ground_color of this ShapeStyleData.
        the background color of shape,like '#000000'

        :return: The back_ground_color of this ShapeStyleData.
        :rtype: str
        """
        return self.container['back_ground_color']

    @back_ground_color.setter
    def back_ground_color(self, back_ground_color):
        """
        Sets the back_ground_color of this ShapeStyleData.
        the background color of shape,like '#000000'

        :param back_ground_color: The back_ground_color of this ShapeStyleData.
        :type: str
        """

        self.container['back_ground_color'] = back_ground_color

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.get_swagger_types()):
            value = self.get_from_container(attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ShapeStyleData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
