# coding: utf-8

"""
    Aspose.Diagram Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ShapeData(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'pin_x': 'float',
        'pin_y': 'float'
    }

    attribute_map = {
        'id': 'ID',
        'pin_x': 'PinX',
        'pin_y': 'PinY'
    }
    
    @staticmethod
    def get_swagger_types():
        return ShapeData.swagger_types
    
    @staticmethod
    def get_attribute_map():
        return ShapeData.attribute_map
    
    def get_from_container(self, attr):
        if attr in self.container:
            return self.container[attr]
        return None

    def __init__(self, id=None, pin_x=None, pin_y=None, **kw):
        """
        Associative dict for storing property values
        """
        self.container = {}
		    
        """
        ShapeData - a model defined in Swagger
        """

        self.container['id'] = None
        self.container['pin_x'] = None
        self.container['pin_y'] = None

        self.id = id
        self.pin_x = pin_x
        self.pin_y = pin_y

    @property
    def id(self):
        """
        Gets the id of this ShapeData.

        :return: The id of this ShapeData.
        :rtype: int
        """
        return self.container['id']

    @id.setter
    def id(self, id):
        """
        Sets the id of this ShapeData.

        :param id: The id of this ShapeData.
        :type: int
        """
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")
        """

        self.container['id'] = id

    @property
    def pin_x(self):
        """
        Gets the pin_x of this ShapeData.

        :return: The pin_x of this ShapeData.
        :rtype: float
        """
        return self.container['pin_x']

    @pin_x.setter
    def pin_x(self, pin_x):
        """
        Sets the pin_x of this ShapeData.

        :param pin_x: The pin_x of this ShapeData.
        :type: float
        """
        """
        if pin_x is None:
            raise ValueError("Invalid value for `pin_x`, must not be `None`")
        """

        self.container['pin_x'] = pin_x

    @property
    def pin_y(self):
        """
        Gets the pin_y of this ShapeData.

        :return: The pin_y of this ShapeData.
        :rtype: float
        """
        return self.container['pin_y']

    @pin_y.setter
    def pin_y(self, pin_y):
        """
        Sets the pin_y of this ShapeData.

        :param pin_y: The pin_y of this ShapeData.
        :type: float
        """
        """
        if pin_y is None:
            raise ValueError("Invalid value for `pin_y`, must not be `None`")
        """

        self.container['pin_y'] = pin_y

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.get_swagger_types()):
            value = self.get_from_container(attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ShapeData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
